import type { SupportedLanguage } from "@/lib/i18n";

type FinancialTermEntry = {
  en: string;
  zh: string;
  descriptionEn: string;
  descriptionZh: string;
  aliases?: string[];
};

const financialTerms: FinancialTermEntry[] = [
  {
    en: "P/E (TTM)",
    zh: "本益比（TTM）",
    descriptionEn: "Shows how many times current earnings investors are paying for.",
    descriptionZh: "市場願意給目前獲利多少倍數",
  },
  {
    en: "Forward P/E",
    zh: "預估本益比",
    descriptionEn: "Compares the stock price with expected future earnings.",
    descriptionZh: "股價相對未來獲利預期是否偏貴",
  },
  {
    en: "P/S (TTM)",
    zh: "市銷率（TTM）",
    descriptionEn: "Compares valuation with revenue and is useful when earnings are weak.",
    descriptionZh: "估值相對營收高不高，虧損公司也常用",
  },
  {
    en: "P/B",
    zh: "股價淨值比",
    descriptionEn: "Compares the stock price with the company's book value.",
    descriptionZh: "股價相對公司淨值高不高",
  },
  {
    en: "EV/EBITDA",
    zh: "EV/EBITDA",
    descriptionEn: "Useful for comparing core cash earnings across companies.",
    descriptionZh: "方便比較不同公司的本業現金獲利能力",
  },
  {
    en: "Revenue",
    zh: "營收",
    descriptionEn: "Shows business scale and top-line growth.",
    descriptionZh: "公司規模與成長動能",
  },
  {
    en: "Gross Profit",
    zh: "毛利",
    descriptionEn: "Shows how much profit remains after direct costs.",
    descriptionZh: "扣除直接成本後還剩多少利潤",
  },
  {
    en: "Gross Margin (%)",
    zh: "毛利率 (%)",
    descriptionEn: "Shows pricing power and cost pressure.",
    descriptionZh: "產品價格力與成本壓力",
  },
  {
    en: "Selling & Marketing Exp",
    zh: "銷售與行銷費用",
    descriptionEn: "Shows how much the company spends to win customers and support sales.",
    descriptionZh: "公司為了拓客與銷售投入多少費用",
  },
  {
    en: "R&D Exp",
    zh: "研發費用",
    descriptionEn: "Shows how much the company is investing in technology and new products.",
    descriptionZh: "公司對技術與新產品的投入",
  },
  {
    en: "General & Admin Exp",
    zh: "管理費用",
    descriptionEn: "Shows the level of corporate overhead and back-office costs.",
    descriptionZh: "管理與後勤等固定成本高不高",
  },
  {
    en: "Operating Income",
    zh: "營業利益",
    descriptionEn: "Shows profit generated by the core business.",
    descriptionZh: "本業到底賺不賺錢",
  },
  {
    en: "Operating Margin (%)",
    zh: "營業利益率 (%)",
    descriptionEn: "Shows how much operating profit is kept from each unit of revenue.",
    descriptionZh: "每單位營收能留下多少本業利潤",
  },
  {
    en: "Net Income",
    zh: "淨利",
    descriptionEn: "Shows the final profit after all costs and non-operating items.",
    descriptionZh: "扣掉所有成本後的最終獲利",
  },
  {
    en: "Net Margin (%)",
    zh: "淨利率 (%)",
    descriptionEn: "Shows how much final profit is kept from each unit of revenue.",
    descriptionZh: "每單位營收最後能留下多少淨利",
  },
  {
    en: "Op Cash Flow",
    zh: "營業現金流",
    descriptionEn: "Shows whether profits are turning into real operating cash.",
    descriptionZh: "獲利有沒有真正變成現金流入",
  },
  {
    en: "Investing Cash Flow",
    zh: "投資現金流",
    descriptionEn: "Shows cash spent on or received from investments and asset purchases.",
    descriptionZh: "公司在投資、買資產或處分資產的現金變化",
  },
  {
    en: "Financing Cash Flow",
    zh: "融資現金流",
    descriptionEn: "Shows cash raised from or returned to lenders and shareholders.",
    descriptionZh: "公司在借款、還債、增資或配息的現金變化",
  },
  {
    en: "CAPEX",
    zh: "資本支出",
    descriptionEn: "Shows spending on plants, equipment, and future capacity.",
    descriptionZh: "公司對廠房、設備與未來產能的投資",
  },
  {
    en: "Millions TWD",
    zh: "百萬新台幣",
    descriptionEn: "Values are shown in millions of New Taiwan dollars.",
    descriptionZh: "數值單位為百萬新台幣",
    aliases: ["百萬台幣", "百萬新台幣"],
  },
];

const phrasePairs = [
  ["財務摘要", "Financial Summary"],
  ["估值指標", "Valuation Metrics"],
  ["年度關鍵財務數據", "Annual Financials"],
  ["季度關鍵財務數據", "Quarterly Financials"],
  ["近 3 年", "Last 3 Years"],
  ["近 4 季", "Last 4 Quarters"],
  ["單位: 百萬新台幣, 僅 Margin 為%", "Unit: TWD mn, only margin rows are shown in %"],
  ["單位：百萬新台幣，僅 Margin 為%", "Unit: TWD mn, only margin rows are shown in %"],
  ["單位: 百萬台幣, 僅 Margin 為%", "Unit: TWD mn, only margin rows are shown in %"],
  ["單位：百萬台幣，僅 Margin 為%", "Unit: TWD mn, only margin rows are shown in %"],
  ["股價", "Share price"],
  ["截至", "through"],
  ["預估至", "forecast through"],
  ["百萬新台幣", "Millions TWD"],
  ["百萬台幣", "Millions TWD"],
] as const;

const translationPairs = [
  ...phrasePairs,
  ...financialTerms.map((term) => [term.zh, term.en] as const),
];

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function normalizeKey(value: string) {
  return value.trim().replace(/\s+/g, " ");
}

function buildReplacements(language: SupportedLanguage) {
  const basePairs =
    language === "en"
      ? translationPairs
      : translationPairs.map(([zh, en]) => [en, zh] as const);

  return [...basePairs].sort((a, b) => b[0].length - a[0].length);
}

const definitionLookup = new Map<string, FinancialTermEntry>();

for (const term of financialTerms) {
  definitionLookup.set(normalizeKey(term.en), term);
  definitionLookup.set(normalizeKey(term.zh), term);

  for (const alias of term.aliases ?? []) {
    definitionLookup.set(normalizeKey(alias), term);
  }
}

export function translateFinancialText(
  text: string,
  language: SupportedLanguage,
) {
  if (!text) {
    return text;
  }

  return buildReplacements(language).reduce((output, [from, to]) => {
    return output.replace(new RegExp(escapeRegExp(from), "g"), to);
  }, text);
}

export function getFinancialTermDescription(
  text: string,
  language: SupportedLanguage,
) {
  const term = definitionLookup.get(normalizeKey(text));

  if (!term) {
    return null;
  }

  return language === "en" ? term.descriptionEn : term.descriptionZh;
}
